/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The brandable one-call helper (`SPEC.md` §2, §7.2): pair the upstream surface
 * with a policy and gate an MCP through it in two calls.
 *
 * Construct `new Guard(upstreamJson, policyJson)` from the app's full tool defs
 * plus the projection to enforce; then register [`slimDefs`](Self::slim_defs)
 * as the downstream `tools/list` and run every incoming `tools/call` through
 * [`gate`](Self::gate) — no `project`/`rewrite` plumbing, no policy threading at
 * each call site. All branding (renamed names, slim descriptions, dropped
 * tools) lives in the policy the app supplies; the helper reads nothing itself.
 * Mirrors [`lagom_core::Guard`] and the Python/Go `Guard` exactly (NO DRIFT).
 */
export declare class Guard {
  /**
   * Build a guard from the upstream tool defs and the policy that narrows them.
   *
   * `upstreamJson` is the app's full `tools/list` array as JSON; `policyJson`
   * is a [`lagom_core::Policy`] as JSON (from `PolicyBuilder.build`, the app's
   * own config, or a literal). The slim surface is projected once here, so a
   * malformed input throws immediately rather than at first use.
   */
  constructor(upstreamJson: string, policyJson: string)
  /**
   * The projected, branded downstream tool defs as a JSON array string — the
   * `tools/list` to advertise. Tools dropped, pinned args pruned, names renamed
   * and descriptions overridden per the policy.
   */
  slimDefs(): string
  /**
   * Gate one incoming downstream `tools/call`.
   *
   * `callJson` uses the downstream (post-rename) tool name and the args the
   * agent supplied through the slim schema. Returns the upstream call as JSON
   * (pinned/default args injected, name mapped back); a rejected call (unknown
   * or dropped tool, violated constraint) throws an `Error` annotated with the
   * violated bound (`SPEC.md` §9.1 — never swallow).
   */
  gate(callJson: string): string
  /**
   * The frozen policy this guard enforces, as a JSON string (e.g. to
   * `validate` against a freshly probed upstream).
   */
  policy(): string
}

/**
 * A typed, fluent builder for a [`lagom_core::Policy`] from TypeScript
 * (`SPEC.md` §6.1).
 *
 * The integrator's type-safe authoring front-end: methods narrow the projection
 * (drop tools, pin/constrain/default args, override descriptions); `build`
 * emits the policy as JSON ready to hand to `project`, `rewrite`, `merge`,
 * `validate`, or `mintStdioServer`. Methods that take a value accept it as a
 * JSON string (e.g. `'"hylla"'`, `'42'`, `'["a","b"]'`), exactly like the
 * Python binding, so the marshalling stays identical across bindings.
 */
export declare class PolicyBuilder {
  /**
   * A passthrough builder: keeps every tool unchanged unless narrowed
   * (`default_presence = keep`).
   */
  constructor()
  /**
   * A sealed builder: drops every tool unless explicitly [`keep`](Self::keep)
   * is called (`default_presence = drop`). The basis of an allowlist sandbox.
   */
  static sealed(): PolicyBuilder
  /** Explicitly keep `tool` (overrides a sealed default presence). */
  keep(tool: string): void
  /** Drop `tool` from the projected surface (`SPEC.md` §4.1). */
  dropTool(tool: string): void
  /** Expose `tool` under a different downstream `name`. */
  rename(tool: string, name: string): void
  /**
   * Replace `tool`'s description with integrator-authored slim text
   * (Tier 1 override, `SPEC.md` §4.2).
   */
  describe(tool: string, text: string): void
  /**
   * Pin `tool`'s `arg` to `value` (given as a JSON string): removed from the
   * projected schema, injected on every call (`SPEC.md` §3, §4.1).
   */
  pin(tool: string, arg: string, valueJson: string): void
  /**
   * Supply `tool`'s `arg` with `value` (JSON string) when the agent omits it;
   * stays visible, unlike [`pin`](Self::pin).
   */
  default(tool: string, arg: string, valueJson: string): void
  /** Constrain `tool`'s `arg` to an enum subset (`valuesJson` is a JSON array). */
  constrainEnum(tool: string, arg: string, valuesJson: string): void
  /**
   * Constrain `tool`'s numeric `arg` to an inclusive `[min, max]` range; either
   * bound may be `null`/omitted (open).
   */
  constrainRange(tool: string, arg: string, min?: number | undefined | null, max?: number | undefined | null): void
  /** Constrain `tool`'s string `arg` to match a regex `pattern`. */
  constrainPattern(tool: string, arg: string, pattern: string): void
  /** Emit the authored policy as a JSON string, ready for the engine functions. */
  build(): string
}

/**
 * Write the shipped skill markdown into `dir` (created if absent), mirroring the
 * CLI's `lagom emit-skills` (`SPEC.md` §12).
 *
 * Returns the list of written file paths (as strings). Like `lagom emit`, lagom
 * does not manage how a harness discovers the files — it just drops them where
 * the consumer asks. `dir` defaults to the current directory. I/O failures throw
 * an `Error`.
 */
export declare function emitSkills(dir?: string | undefined | null): Array<string>

/**
 * Narrow-only merge of an end-user `overlay` onto an integrator `base`
 * (`SPEC.md` §5.2).
 *
 * Both are policies as JSON. Returns the composed policy as JSON. Any attempt to
 * *widen* the sealed bounds (re-add a dropped tool, loosen a constraint, unpin)
 * throws an `Error` — this merge is the sandbox enforcement.
 */
export declare function merge(baseJson: string, overlayJson: string): string

/**
 * Mint an ephemeral per-agent projection in code and return the recorded
 * [`lagom_core::MintRecord`] as JSON (`SPEC.md` §8.1, §8.2).
 *
 * `runId` names the run; `baseJson` is the integrator's sealed-ceiling
 * [`Policy`] as JSON; `dynamicJson` is an optional per-agent narrowing overlay
 * (omit/`null` for none — e.g. a `path` constraint scoping a subagent to the
 * exact files it may touch); `command`/`args`/`env` are how to launch the
 * upstream this projection wraps. Returns a `MintRecord` (resolved policy +
 * provenance) the app persists wherever it likes and later hands to [`refire`]
 * to reproduce the same server. The overlay may only **narrow** the base; any
 * widening throws an `Error` (the sandbox enforcement, `SPEC.md` §5.2).
 * Deterministic: no LLM, no clock, no disk.
 */
export declare function mint(runId: string, baseJson: string, dynamicJson?: string | undefined | null, command?: string | undefined | null, args?: Array<string> | undefined | null, env?: Array<[string, string]> | undefined | null): string

/**
 * Mint a stdio proxy server for `policyJson` over a spawned upstream and serve
 * it on this process's stdio until the session ends (`SPEC.md` §7.2, §8, §10).
 *
 * `policyJson` is the projection to enforce; `command`/`args`/`env` are how to
 * launch the upstream MCP server as a child process (`env` as `[key, value]`
 * pairs). lagom spawns the child, validates the policy against its live
 * `tools/list` (failing loud on drift), then bridges JSON-RPC between the
 * caller's stdio and the child, applying the transforms in between. **Blocks**
 * the calling thread until the session ends — call it from the process whose
 * stdio should carry the projected surface.
 *
 * With `audit` set to a path the session is routed through
 * [`lagom_proxy::serve_audited`], opening an append-only JSONL log that records
 * the original upstream defs + resolved policy at session start and every
 * rewrite/rejection thereafter, tagged with `runId` (`SPEC.md` §8.2, §9.3) —
 * mirroring the CLI's `--audit`/`--run-id`. The log's parent directory must
 * already exist. Without `audit` no log is written and behavior is unchanged;
 * `runId` defaults to `run` and is only meaningful with `audit`.
 *
 * Drift, a widening overlay, a child-spawn failure, or an audit-log open
 * failure throw an `Error`.
 */
export declare function mintStdioServer(policyJson: string, command: string, args?: Array<string> | undefined | null, env?: Array<[string, string]> | undefined | null, audit?: string | undefined | null, runId?: string | undefined | null): void

/**
 * Project an upstream tool surface through a policy (`SPEC.md` §3, §4).
 *
 * `upstreamJson` is the upstream `tools/list` array of tool defs as JSON;
 * `policyJson` is a [`lagom_core::Policy`] as JSON (e.g. from
 * `PolicyBuilder.build`). Returns the projected surface as a JSON array
 * string — tools dropped, pinned args pruned from schemas, constraints applied.
 */
export declare function project(upstreamJson: string, policyJson: string): string

/**
 * Re-mint the recorded resolved policy from a persisted mint record
 * (refire, `SPEC.md` §8.2).
 *
 * `recordJson` is a [`lagom_core::MintRecord`] as JSON (as returned by
 * [`mint`]). Returns the [`lagom_core::ResolvedPolicy`] as JSON ready to serve —
 * the exact projection the original run had, reproduced without re-resolution. A
 * malformed record throws an `Error`.
 */
export declare function refire(recordJson: string): string

/**
 * Rewrite a projected call back into the upstream call, or throw on reject
 * (`SPEC.md` §4, §9).
 *
 * `callJson` is a [`lagom_core::ToolCall`] as JSON; `policyJson` is the policy.
 * Returns the upstream call as JSON (pinned/default args injected); a rejected
 * call (unknown tool, violated constraint) throws an `Error` annotated with the
 * violated bound.
 */
export declare function rewrite(callJson: string, policyJson: string): string

/**
 * The shipped lagom **skills** (`SPEC.md` §12) bundled in this binding, as an
 * array of `[filename, body]` tuples.
 *
 * Identical bytes to the CLI's `lagom emit-skills`: both faces embed the same
 * canonical markdown from `lagom-proxy`. A host loads these inert documents to
 * learn how to use lagom well; lagom never loads or runs them itself.
 */
export declare function shippedSkills(): Array<Array<string>>

/**
 * Validate a policy against the live upstream tool surface (`SPEC.md` §5.3).
 *
 * `policyJson` is the policy; `upstreamJson` is the upstream tool defs as JSON.
 * Resolves with no value on success; on drift (a policy reference no longer
 * matches the upstream) throws an `Error` carrying every per-reference drift
 * message — serving must be refused.
 */
export declare function validate(policyJson: string, upstreamJson: string): void
